name: Build and deploy ASP.Net Core app to Azure Web App - fhueiwfhhoiew

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore eShopOnWeb.sln

      - name: Build solution
        run: dotnet build eShopOnWeb.sln --configuration Release --no-restore

      - name: Install EF Core tool
        run: dotnet tool install --global dotnet-ef

      - name: Apply database migrations
        env:
          CatalogConnection: "Server=tcp:abc-sandbox-app-server.database.windows.net,1433;Initial Catalog=abc-sandbox-app-catalog;User ID=abc-sandbox-app-server-admin;Password=eP7SKTVae4wC$VT7;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
          IdentityConnection: "Server=tcp:abc-sandbox-app-server.database.windows.net,1433;Initial Catalog=abc-sandbox-app-identity;User ID=abc-sandbox-app-server-admin;Password=eP7SKTVae4wC$VT7;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
        run: |
          export PATH="$PATH:$HOME/.dotnet/tools"
          dotnet ef database update -c CatalogContext -p ./src/Infrastructure/Infrastructure.csproj -s ./src/Web/Web.csproj --connection "$CatalogConnection"
          dotnet ef database update -c AppIdentityDbContext -p ./src/Infrastructure/Infrastructure.csproj -s ./src/Web/Web.csproj --connection "$IdentityConnection"

      - name: Publish
        run: dotnet publish eShopOnWeb.sln -c Release -o ${{env.DOTNET_ROOT}}/myapp --no-restore

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C6634FBCE8944BECA2F76BA620090298 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5177581878F84596971BFA421373FE9B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6A780997BC4D4A949BE8752808C48356 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fhueiwfhhoiew'
          slot-name: 'Production'
          package: ${{env.DOTNET_ROOT}}/myapp
